Register bindings and widgets for the key `d`
kutsan/zsh-system-clipboard pull request #8
Opened 2018-08-05 17:00 UTC by doronbehar

2018-08-05 19:48 UTC, kutsan requested changes
Thanks for your PR!

But we shouldn't repeat ourselves. I think for this case this is enough:

```zsh
function zsh-system-clipboard-key-d() {
	zsh-system-clipboard-key-x
}
```

2018-08-06 17:01 UTC, doronbehar commented
I agree ^

2018-08-06 22:00 UTC, kutsan approved these changes

2018-08-06 22:00 UTC, merged

2018-08-06 22:00 UTC, kutsan commented
Thanks again!